# Generated by Django 6.0.2 on 2026-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Financial', 'Financial'), ('Personal', 'Personal')], max_length=50),
        ),
    ]
