# Generated by Django 6.0.2 on 2026-02-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_ai_summary_alter_document_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='raw_text',
            new_name='text',
        ),
    ]
